## SAMPLES AND SAMPLE-SPECIFIC PARAMETERS ==========================================================

# sample id: /path/to/fastq/directory
samples:
  Sample10X:   /g/steinmetz/incoming/solexa/2018-11-22-H3372BGX9/lane1/LIB38089_RBA37572/fastq
  11iv210ng:   /g/steinmetz/incoming/solexa/2018-11-22-H3372BGX9/lane1/LIB38090_RBA37573/fastq
  11iv22ng:    /g/steinmetz/incoming/solexa/2018-11-22-H3372BGX9/lane1/LIB38091_RBA37574/fastq
  8iv210ng:    /g/steinmetz/incoming/solexa/2018-11-22-H3372BGX9/lane1/LIB38087_RBA37570/fastq
  8iv22ng:     /g/steinmetz/incoming/solexa/2018-11-22-H3372BGX9/lane1/LIB38088_RBA37571/fastq
  8iScreen1:   /g/steinmetz/project/singcellTxn/CRISPRdrop/10X_RAW_DATA/k562_screen_Feb2019/8iScreen1
  11iScreen1:  /g/steinmetz/project/singcellTxn/CRISPRdrop/10X_RAW_DATA/k562_screen_Feb2019/11iScreen1
  WholeTx:     /g/steinmetz/project/singcellTxn/CRISPRdrop/10X_RAW_DATA/cropseq_vs_tapseq_may2019/WholeTx
  TAP1:        /g/steinmetz/incoming/solexa/2019-04-17-H5HTFBDXX/lane1/LIB43383_RBA42866/fastq
  TAP2:        /g/steinmetz/incoming/solexa/2019-04-17-H5HTFBDXX/lane1/LIB43382_RBA42865/fastq
  re-wholetx:  /g/steinmetz/incoming/solexa/2019-06-28-HJNGJBGXB/lane1/LIB45917_RBA45400/fastq
  re11iv210ng: /g/steinmetz/incoming/solexa/2019-06-28-HJNGJBGXB/lane1/LIB45918_RBA45401/fastq
  DanielUnclear: /g/steinmetz/schraivo
  W4ea: /g/steinmetz/incoming/solexa/2017-11-07-HW3MVBGX3/lane1/LIB26096_RBA25548/fastq
  T4ea: /g/steinmetz/incoming/solexa/2017-11-07-HW3MVBGX3/lane1/LIB26093_RBA25545/fastq
  # mouse cell type mix:
  wtxmmix: /g/steinmetz/incoming/solexa/2019-12-11-HNW3JBGXC/lane1/LIB49660_RBA49151/fastq
  wtxlung: /g/steinmetz/incoming/solexa/2019-12-11-HNW3JBGXC/lane1/LIB49661_RBA49152/fastq
  tapmix:  /g/steinmetz/incoming/solexa/2019-12-17-HYG5TBGXC/lane1/LIB49694_RBA49185/fastq
  taplung: /g/steinmetz/incoming/solexa/2019-12-17-HYG5TBGXC/lane1/LIB49692_RBA49183/fastq
  # human cell type mix:
  19s005246: /g/steinmetz/incoming/solexa/2019-12-17-HNTWCBGXC/lane1/LIB49711_RBA49202/fastq
  taphumanmix: /g/steinmetz/incoming/solexa/2019-12-17-HYG5TBGXC/lane1/LIB49693_RBA49184/fastq

# estimated number of cells per sample, for which dge data should be extracted.
cell_numbers:
  Sample10X:   8000
  11iv210ng:   8500
  11iv22ng:    8500
  8iv210ng:    7500
  8iv22ng:     7500
  8iScreen1:   112000
  11iScreen1:  120000
  WholeTx:     38000
  TAP1:        11000
  TAP2:        11000
  re-wholetx:  8000
  re11iv210ng: 8500
  DanielUnclear: 19000
  W4ea: 5000
  T4ea: 5000
  wtxmmix: 400
  wtxlung: 200
  tapmix:  325
  taplung: 130
  19s005246: 750
  taphumanmix: 400
  
# cell and umi barcode base positions in barcode reads for each sample. the first element of the
# array is the cell barcode range, while the second is the UMI barcode range. for screen samples the
# i7 sample barcode was added to the cell barcode, to avoid barcode collisions because multiple 10X
# lanes were multiplexed.
bc_structure:
  Sample10X:   [1-16, 17-26]
  11iv210ng:   [1-16, 17-26]
  11iv22ng:    [1-16, 17-26]
  8iv210ng:    [1-16, 17-26]
  8iv22ng:     [1-16, 17-26]
  8iScreen1:   [1-24, 25-34]
  11iScreen1:  [1-24, 25-34]
  WholeTx:     [1-24, 25-34]
  TAP1:        [1-16, 17-26]
  TAP2:        [1-16, 17-26]
  re-wholetx:  [1-16, 17-26]
  re11iv210ng: [1-16, 17-26]
  DanielUnclear: [1-16, 17-26]
  W4ea: [1-12, 13-20]
  T4ea: [1-12, 13-20]
  wtxmmix: [1-16, 17-26]
  wtxlung: [1-16, 17-26]
  tapmix:  [1-16, 17-26]
  taplung: [1-16, 17-26]
  19s005246: [1-16, 17-26]
  taphumanmix: [1-16, 17-26]
  
# alignment reference for each sample
align_ref:
  Sample10X:   data/alignment_references/hg38_genome_ref
  11iv210ng:   data/alignment_references/hg38_tapseq_ref_validation
  11iv22ng:    data/alignment_references/hg38_tapseq_ref_validation
  8iv210ng:    data/alignment_references/hg38_tapseq_ref_validation
  8iv22ng:     data/alignment_references/hg38_tapseq_ref_validation
  8iScreen1:   data/alignment_references/hg38_tapseq_ref_chr8_screen
  11iScreen1:  data/alignment_references/hg38_tapseq_ref_chr11_screen
  WholeTx:     data/alignment_references/hg38_genome_ref_v2
  TAP1:        data/alignment_references/hg38_tapseq_ref_validation_v2
  TAP2:        data/alignment_references/hg38_tapseq_ref_validation_v2
  re-wholetx:  data/alignment_references/hg38_genome_ref
  re11iv210ng: data/alignment_references/hg38_tapseq_ref_validation
  DanielUnclear: data/alignment_references/hg38_tapseq_ref_validation_v3
  W4ea:  data/alignment_references/hg38_genome_ref_dropseq
  T4ea:  data/alignment_references/hg38_tapseq_ref_dropseq
  wtxmmix: data/alignment_references/mm10_genome_ref
  wtxlung: data/alignment_references/mm10_genome_ref
  tapmix:  data/alignment_references/mm10_tapseq_ref_mix
  taplung: data/alignment_references/mm10_tapseq_ref_mix
  19s005246: data/alignment_references/hg38_genome_ref_mix
  taphumanmix: data/alignment_references/hg38_tapseq_ref_mix
  
# number of minimum molecules per CROP-seq vector to define a cell perturbed for a given vector
perturbation_status:
  min_txs:
    Sample10X:   4
    11iv210ng:   8
    11iv22ng:    8
    8iv210ng:    8
    8iv22ng:     8
    8iScreen1:   8
    11iScreen1:  8
    WholeTx:     8
    TAP1:        8
    TAP2:        8
    re-wholetx:  8
    re11iv210ng: 8
    DanielUnclear: 8
    W4ea: 2
    T4ea: 8
    
# sample ids for different experiments
validation:   [11iv210ng, 11iv22ng, 8iv210ng, 8iv22ng, Sample10X]
screen:       [8iScreen1, 11iScreen1]
tap_vs_whole: [WholeTx, TAP1, TAP2]
drop-seq:     [W4ea, T4ea]
mouse_mix:    [wtxmmix, wtxlung, tapmix, taplung]
human_mix:    [19s005246, taphumanmix]

## PARAMETERS FOR INDIVIDUAL RULES =================================================================

# step 1: create alignment reference ---------------------------------------------------------------
download_genome_annot:
  hg38:
    fasta_url: ftp://ftp.ensembl.org/pub/release-89/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
    gtf_url: ftp://ftp.ensembl.org/pub/release-89/gtf/homo_sapiens/Homo_sapiens.GRCh38.89.gtf.gz
  mm10:
    fasta_url: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M20/GRCm38.primary_assembly.genome.fa.gz
    gtf_url: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M20/gencode.vM20.annotation.gtf.gz

create_tapseq_ref:
  target_genes: 
    hg38_tapseq_ref_validation:    meta_data/target_gene_panels/target_genes_validation.gtf
    hg38_tapseq_ref_chr8_screen:   meta_data/target_gene_panels/target_genes_chr8_screen.gtf
    hg38_tapseq_ref_chr11_screen:  meta_data/target_gene_panels/target_genes_chr11_screen.gtf
    hg38_tapseq_ref_validation_v2: meta_data/target_gene_panels/target_genes_validation_v2.gtf
    hg38_tapseq_ref_validation_v3: meta_data/target_gene_panels/target_genes_validation.gtf
    hg38_tapseq_ref_dropseq: meta_data/target_gene_panels/target_genes_validation.gtf
    hg38_tapseq_ref_rev: meta_data/target_gene_panels/target_genes_chr8_rev.gtf
    mm10_tapseq_ref_mix: meta_data/target_gene_panels/target_genes_mouse_mix.gtf
    hg38_tapseq_ref_mix: meta_data/target_gene_panels/target_genes_chr8_rev.gtf
    hg38_tapseq_ref_l1000: meta_data/target_gene_panels/target_genes_L1000.gtf.gz
  BSgenome_id: 
    hg38: BSgenome.Hsapiens.UCSC.hg38
    mm10: BSgenome.Mmusculus.UCSC.mm10
  
create_vector_ref:
  vector_fasta:
    hg38_genome_ref:    meta_data/cropseq_vectors/cropseq_vectors_validation.fasta
    hg38_genome_ref_v2: meta_data/cropseq_vectors/cropseq_vectors_validation_v2.fasta
    hg38_genome_ref_dropseq: meta_data/cropseq_vectors/cropseq_vectors_dropseq.fasta
    hg38_genome_ref_rev: meta_data/cropseq_vectors/cropseq_vectors_rev.fasta
    hg38_tapseq_ref_validation:    meta_data/cropseq_vectors/cropseq_vectors_validation.fasta
    hg38_tapseq_ref_chr8_screen:   meta_data/cropseq_vectors/cropseq_vectors_chr8_screen.fasta
    hg38_tapseq_ref_chr11_screen:  meta_data/cropseq_vectors/cropseq_vectors_chr11_screen.fasta
    hg38_tapseq_ref_validation_v2: meta_data/cropseq_vectors/cropseq_vectors_validation_v2.fasta
    hg38_tapseq_ref_validation_v3: meta_data/cropseq_vectors/cropseq_vectors_chr8_screen.fasta
    hg38_tapseq_ref_dropseq: meta_data/cropseq_vectors/cropseq_vectors_dropseq.fasta
    hg38_tapseq_ref_rev: meta_data/cropseq_vectors/cropseq_vectors_rev.fasta
    hg38_tapseq_ref_l1000: meta_data/cropseq_vectors/cropseq_vectors_rev.fasta
  vector_prefix:
    "CROPseq_dCas9_DS_"
  
create_genomedir:
  threads: 5
  sjdb_overhang: 57
  
# step 2: align reads ------------------------------------------------------------------------------
tag_cell_barcodes:
  base_quality: 10
  num_bases_below_quality: 1

tag_molecule_barcodes:
  base_quality: 10
  num_bases_below_quality: 1

trim_starting_sequence:
  adapter_sequence: AAGCAGTGGTATCAACGCAGAGTGAATGGG
  mismatches: 0
  num_bases: 5

trim_polyA:
  mismatches: 0
  num_bases: 6

star_align:
  threads: 5

bead_synthesis_error:
  min_umis_per_cell: 25
  max_num_errors: 1
  read_mq: 10
  primer_sequence: null
  edit_distance: 0
  
reads_per_cell:
  read_quality: 10
  
# step 3: extract dge data -------------------------------------------------------------------------
umi_observations:
  edit_distance: 1
  read_mq: 10
  min_umi_reads: 0
  rare_umi_filter_threshold: 0.0
  
extract_dge:
  tpt_threshold: 0.25
    
# step 4: analyses ---------------------------------------------------------------------------------
downsample:
  reads_per_cell:
    Sample10X: [1000, 1500, 3500, 5000, 10000, 15000, 20000]
    tap-seq:   [1000, 1500, 3500]
    re-wholetx:  [1000, 1500, 3500, 5000, 10000]
    re11iv210ng: [1000, 1500, 3500, 5000, 10000, 15000, 20000, 30000]
    DanielUnclear: [1000, 1500, 3500, 5000, 7000]
    W4ea: [1000]
    T4ea: [1000, 1500, 3500, 5000, 10000, 15000]
    wtxmmix: [1000, 1500, 3500, 5000, 10000, 15000, 20000, 40000, 80000, 160000, 320000]
    wtxlung: [1000, 1500, 3500, 5000, 10000, 15000, 20000, 40000, 80000, 160000]
    tapmix:  [1000, 1500, 3500, 5000, 10000, 15000, 20000, 40000, 80000, 160000, 320000]
    taplung: [1000, 1500, 3500, 5000, 10000, 15000, 20000, 40000, 80000, 160000, 320000]
    19s005246:   [1000, 1500, 3500, 5000, 10000, 15000, 20000, 40000, 80000, 160000, 250000]
    taphumanmix: [1000, 1500, 3500, 5000, 10000, 15000, 20000, 40000, 80000, 160000, 250000, 500000]
    
collapse_perturbations:
  targets:
    8iScreen1:  "meta_data/vector_targets_chr8_screen.csv"
    11iScreen1: "meta_data/vector_targets_chr11_screen.csv"
 
map_enhancers:
  remove_lanes:
    8iScreen1:  ["none"]
    11iScreen1: ["CATCGACC"]
  min_cells:
    perEnh:  25
    perGRNA: 15
  threads: 5
  
chromatin_analyses:
  encode_chip:
    H3K27ac:  "https://www.encodeproject.org/files/ENCFF779QTH/@@download/ENCFF779QTH.bigWig"
    H3K4me1:  "https://www.encodeproject.org/files/ENCFF761XBZ/@@download/ENCFF761XBZ.bigWig"
    H3K4me3:  "https://www.encodeproject.org/files/ENCFF712XRE/@@download/ENCFF712XRE.bigWig"
    H3K27me3: "https://www.encodeproject.org/files/ENCFF928NWQ/@@download/ENCFF928NWQ.bigWig"
    POLR2A:   "https://www.encodeproject.org/files/ENCFF321FZQ/@@download/ENCFF321FZQ.bigWig"
  encode_bam:
    H3K27ac:   "https://www.encodeproject.org/files/ENCFF301TVL/@@download/ENCFF301TVL.bam"
    H3K4me1:   "https://www.encodeproject.org/files/ENCFF290LQY/@@download/ENCFF290LQY.bam"
    H3K4me3:   "https://www.encodeproject.org/files/ENCFF611YPB/@@download/ENCFF611YPB.bam"
    H3K27me3:  "https://www.encodeproject.org/files/ENCFF915XIL/@@download/ENCFF915XIL.bam"
    POLR2A:    "https://www.encodeproject.org/files/ENCFF438GBD/@@download/ENCFF438GBD.bam"
    Dnase-seq: "https://www.encodeproject.org/files/ENCFF538GKX/@@download/ENCFF538GKX.bam"
  rao_hic: "ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE63nnn/GSE63525/suppl/GSE63525_K562_intrachromosomal_contact_matrices.tar.gz"
