## SAMPLES AND SAMPLE-SPECIFIC PARAMETERS ==========================================================

# sample id: /path/to/fastq/directory
samples:
  Sample10X:  /g/steinmetz/incoming/solexa/2018-11-22-H3372BGX9/lane1/LIB38089_RBA37572/fastq
  11iv210ng:  /g/steinmetz/incoming/solexa/2018-11-22-H3372BGX9/lane1/LIB38090_RBA37573/fastq
  11iv22ng:   /g/steinmetz/incoming/solexa/2018-11-22-H3372BGX9/lane1/LIB38091_RBA37574/fastq
  8iv210ng:   /g/steinmetz/incoming/solexa/2018-11-22-H3372BGX9/lane1/LIB38087_RBA37570/fastq
  8iv22ng:    /g/steinmetz/incoming/solexa/2018-11-22-H3372BGX9/lane1/LIB38088_RBA37571/fastq
  8iScreen1:  /g/steinmetz/project/singcellTxn/CRISPRdrop/10X_RAW_DATA/k562_screen_Feb2019/8iScreen1
  11iScreen1: /g/steinmetz/project/singcellTxn/CRISPRdrop/10X_RAW_DATA/k562_screen_Feb2019/11iScreen1

# rough A PRIORI estimate of the number of sequenced cells per sample. this is only used for plots
# in the alignment report and does not impact generated output data
expect_cell_numbers:
  Sample10X:  10000
  11iv210ng:  8000
  11iv22ng:   8000
  8iv210ng:   8000
  8iv22ng:    8000
  8iScreen1:  100000
  11iScreen1: 100000

# number of cells for which dge data should be extracted. these can be arrays to extract dge for
# multiple sets of cells per sample
dge_ncells:
  Sample10X:  8000
  11iv210ng:  8500
  11iv22ng:   8500
  8iv210ng:   7500
  8iv22ng:    7500
  8iScreen1:  112000
  11iScreen1: 120000
  
# cell and umi barcode base positions in barcode reads for each sample. the first element of the
# array is the cell barcode range, while the second is the UMI barcode range. for screen samples the
# i7 sample barcode was added to the cell barcode, to avoid barcode collisions because multiple 10X
# lanes were multiplexed.
bc_structure:
  Sample10X:  [1-16, 17-26]
  11iv210ng:  [1-16, 17-26]
  11iv22ng:   [1-16, 17-26]
  8iv210ng:   [1-16, 17-26]
  8iv22ng:    [1-16, 17-26]
  8iScreen1:  [1-24, 25-34]
  11iScreen1: [1-24, 25-34]

# alignment reference for each sample
align_ref:
  Sample10X:  data/genome_reference
  11iv210ng:  data/tapseq_ref_validation
  11iv22ng:   data/tapseq_ref_validation
  8iv210ng:   data/tapseq_ref_validation
  8iv22ng:    data/tapseq_ref_validation
  8iScreen1:  data/tapseq_ref_chr8_screen
  11iScreen1: data/tapseq_ref_chr11_screen
  
# number of minimum molecules per CROP-seq vector to define a cell perturbed for a given vector
perturbation_status:
  min_txs:
    Sample10X:  4
    11iv210ng:  8
    11iv22ng:   8
    8iv210ng:   8
    8iv22ng:    8
    8iScreen1:  8
    11iScreen1: 8

# sample ids for validation and screen TAP-seq runs
validation: [11iv210ng, 11iv22ng, 8iv210ng, 8iv22ng, Sample10X]
screen:     [8iScreen1, 11iScreen1]

## PARAMETERS FOR INDIVIDUAL RULES =================================================================

# step 1: create alignment reference ---------------------------------------------------------------
download_genome_annot:
  fasta_url: ftp://ftp.ensembl.org/pub/release-89/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
  gtf_url: ftp://ftp.ensembl.org/pub/release-89/gtf/homo_sapiens/Homo_sapiens.GRCh38.89.gtf.gz
  
create_tapseq_ref:
  target_genes: 
    tapseq_ref_validation:   meta_data/target_genes_validation.gtf
    tapseq_ref_chr8_screen:  meta_data/target_genes_chr8_screen.gtf
    tapseq_ref_chr11_screen: meta_data/target_genes_chr11_screen.gtf
  BSgenome_id: BSgenome.Hsapiens.UCSC.hg38
  
create_vector_ref:
  vector_fasta:
    genome_reference: meta_data/cropseq_vectors_validation.fasta
    tapseq_ref_validation:   meta_data/cropseq_vectors_validation.fasta
    tapseq_ref_chr8_screen:  meta_data/cropseq_vectors_chr8_screen.fasta
    tapseq_ref_chr11_screen: meta_data/cropseq_vectors_chr11_screen.fasta
  vector_prefix:
    "CROPseq_dCas9_DS_"
  
create_genomedir:
  star_threads: 5
  sjdb_overhang: 57
  
# step 2: align reads ------------------------------------------------------------------------------
tag_cell_barcodes:
  base_quality: 10
  num_bases_below_quality: 1

tag_molecule_barcodes:
  base_quality: 10
  num_bases_below_quality: 1

trim_starting_sequence:
  adapter_sequence: AAGCAGTGGTATCAACGCAGAGTGAATGGG
  mismatches: 0
  num_bases: 5

trim_polyA:
  mismatches: 0
  num_bases: 6

star_align:
  threads: 5

bead_synthesis_error:
  min_umis_per_cell: 25
  max_num_errors: 1
  read_mq: 10
  primer_sequence: null
  edit_distance: 0
  
reads_per_cell:
  read_quality: 10
  
# step 3: extract dge data -------------------------------------------------------------------------
umi_observations:
  edit_distance: 1
  read_mq: 10
  min_umi_reads: 0
  rare_umi_filter_threshold: 0.0
  
extract_dge:
  tpt_threshold: 0.25
    
# step 4: analysis ---------------------------------------------------------------------------------
downsample:
  reads_per_cell: 3500
 
map_enhancers:
  remove_lanes:
    8iScreen1:  ["none"]
    11iScreen1: ["none"]
  min_cells: 25
  threads: 5
