---
title: "Chromatin analyses enhancer screen"
author: "Andreas Gschwind"
date: "`r format(Sys.time(), '%B %d, %Y')`"
params:
  rmd: "chromatin_analyses_screen.Rmd"
output:
  bookdown::html_document2:
    toc: yes
---

# Goal
In depth chromatin analyses of our enhancer mapping results.

```{css echo=FALSE}
/* Define a margin before every image element */
img {
  margin-top: 3em;
}
```

```{r setup, include=FALSE}
# set global chunk options
knitr::opts_chunk$set(echo = FALSE)

# attach required packages
library(here)
library(rtracklayer)
library(tidyverse)
library(ggpubr)
```

```{r loadData}
# load processed de output (includes confidence level and distance to TSS)
results <- here(snakemake@input$processed_results) %>%
  read.csv(stringsAsFactors = FALSE) %>%
  mutate(sample = paste0("Chr", sub("iScreen1", "", sample)))

# load dge data
dge_files <- here(snakemake@input$dge)
names(dge_files) <- basename(dirname(dge_files))
dge <- lapply(dge_files, FUN = read.table, header = TRUE, row.names = "GENE", 
              stringsAsFactors = FALSE)
```

# Chromatin assays
Chromatin assays from ENCODE are downloaded and enrichment at significant enhancers is compared to
tested, non-significant DNAse sites.

```{r loadChromMarks}
# extract cis enhancer - gene pairs, add label for significant hits and calculate -log10 pvalue
cis_enh_perts <- results %>%
  filter(enh_type == "cis", abs(dist_to_tss) >= 1000) %>%
  mutate(significant = if_else(pval_adj_allTests < 0.05, true = "sig", false = "non_sig"),
         neg_log10_pvalue = -log10(pvalue))

# add "chr" to chromosome for use with ENCODE data
cis_enh_perts <- cis_enh_perts %>%
  mutate(enh_chr = paste0("chr", enh_chr),
         gene_chr = paste0("chr", gene_chr))

# get enhancer coordinates and convert to GRanges object
enh_coords <- cis_enh_perts %>%
  select(enh_chr, enh_start, enh_end, perturbation) %>%
  distinct() %>%
  makeGRangesFromDataFrame(keep.extra.columns = TRUE) %>%
  `names<-`(.$perturbation)  # set names to perturbation id

# download chromatin mark files
chrom_chip_urls <- snakemake@params$encode_chip_urls
chrom_chip_files <- paste0(tempdir(), "/", names(chrom_chip_urls), ".bigWig")
names(chrom_chip_files) <- names(chrom_chip_urls)
mapply(FUN = download.file, chrom_chip_urls, chrom_chip_files)

# load chromatin mark data
chrom_marks <- lapply(chrom_chip_files, FUN = import, which = range(enh_coords), format = "bigWig")
```

```{r chromAtEnhancers}
# function to calculate average assay signal per enhancer
avg_assay_signal <- function(assay, enh_coords) {
  overlaps <- findOverlaps(enh_coords, assay)
  overlaps <- split(overlaps, from(overlaps))
  names(overlaps) <- names(enh_coords[as.numeric(names(overlaps))])
  sapply(overlaps, function(x) {
    sum(mcols(assay[to(x)])$score * width(assay[to(x)])) / sum(width(assay[to(x)]))
  })
}

# calculate average chromatin signal at enhancers
enh_chrom_signal <- sapply(chrom_marks, FUN = avg_assay_signal, enh_coords = enh_coords)

# transform to data.frame and merge with cis enhancer - gene pairs
cis_enh_perts <- enh_chrom_signal %>%
  as.data.frame() %>%
  rownames_to_column(var = "perturbation") %>%
  left_join(x = cis_enh_perts, y = ., by = "perturbation")
```

```{r normalizeDistance}
# create distance to TSS bins
dtss_range <- range(cis_enh_perts$dist_to_tss)
bins <- seq(from = dtss_range[1], to = dtss_range[2], by = 1e4)

# bin distance to tss
cis_enh_perts <- cis_enh_perts %>%
  mutate(dTSS_bin = cut(dist_to_tss, bins))

# calculate number of pairs per bin
pairs_per_bin <- table(table(cis_enh_perts$dTSS_bin))

# function to randomly draw n non-significant pairs for a significant association
draw_control_pairs <- function(sig_assoc, nonSig_assocs, n, replace = FALSE) {
  
  # get non-significant associations on the same chromosome and within the same distance to TSS bin
  nonSig_chr <- nonSig_assocs %>%
    filter(enh_chr == sig_assoc$enh_chr & dTSS_bin == sig_assoc$dTSS_bin)
  
  # randomly draw n controls from that bin (if n > nonSig_chr, then return all...)
  if (nrow(nonSig_chr) >= n) {
    sample_n(nonSig_chr, size = n, replace = replace)
  }else{
    warning("n > available controls! Returning ", nrow(nonSig_chr), " controls...")
    nonSig_chr
  }
  
}

# extract significant associations
sig_assocs <- cis_enh_perts %>%
  filter(significant == "sig") %>%
  filter(perturbation != "GATA1") %>%  # remove GATA1 perturbation, becaus it's the only on chrX
  select(perturbation, enh_chr, gene, dist_to_tss, dTSS_bin, H3K27ac, H3K4me1, H3K4me3, POLR2A) %>%
  distinct()

# get all other enhancers that were tested but appear only in non-sigificant tests
nonSig_assocs <- cis_enh_perts %>%
  filter(significant == "non_sig", !perturbation %in% sig_assocs) %>%
  filter(perturbation != "GATA1") %>%  # remove GATA1 perturbation, becaus it's the only on chrX
  select(perturbation, enh_chr, gene, dist_to_tss, dTSS_bin, H3K27ac, H3K4me1, H3K4me3, POLR2A) %>%
  distinct()

# randomly draw 10 control pairs for each significant association
set.seed(20190529)
nonSig_ctrls <- sig_assocs %>%
  rowwise() %>%
  do(draw_control_pairs(., nonSig_assocs = nonSig_assocs, n = 10))

# combine significant and control pairs
all_pairs <- bind_rows(sig = sig_assocs, non_sig = nonSig_ctrls, .id = "significant")
```

```{r plotChromMarks, fig.width=6, fig.height=5}
# function to test for significance for one chromatin assay
test_wilcox <- function(x) {
  
  # get signal for significant and control enhancers
  sig <- pull(filter(x, significant == "sig"), fc_over_ctrl)
  non_sig <- pull(filter(x, significant == "non_sig"), fc_over_ctrl)
  
  # test and extract p-value
  wilcox_test <- wilcox.test(x = sig, y = non_sig)
  data.frame(pval = wilcox_test$p.value)
  
}

# convert enhancer - gene pairs to long format for plotting
all_pairs_plot <- all_pairs %>%
  gather(key = "assay", value = "fc_over_ctrl",
         -c(significant, perturbation, enh_chr, gene, dist_to_tss, dTSS_bin))

# plot difference in chromatin marks between significant and non-significant associations
ggplot(all_pairs_plot, aes(x = significant, y = fc_over_ctrl + 1, fill = significant)) +
  facet_wrap(~assay, ncol = 2) +
  geom_boxplot(notch = TRUE) +
  stat_compare_means(comparisons =  list(c("sig", "non_sig")), method = "wilcox.test") +
  labs(y = "Chromatin FC over control") +
  scale_x_discrete(labels = c("Non significant", "Significant")) +
  scale_y_log10(limits = c(NA, 180)) +
  scale_fill_manual(values = c(non_sig = "darkgray", sig = "steelblue")) +
  theme_bw() + 
  theme(axis.title.x = element_blank(), legend.position = "none", text = element_text(size = 15),
        panel.grid = element_blank(), strip.background = element_rect(fill = "gray90"))

# save plot for manuscript
ggsave(here("results/plots", "chromatin_sig_vs_nonsig.pdf"), device = "pdf", width = 6,
       height = 5)
```

# HiC
```{r downloadHiC, eval = FALSE}
# download contact matrices
hic_file <- "/g/steinmetz/gschwind/data/HiC/hic.tar.gz"
download.file(snakemake@params$rao_hic, destfile = hic_file)
system(paste("tar -xvzf", hic_file))
```
